// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEMabNu_8ic25ndCfbzfUeJ2_fawGNKQg',
    appId: '1:614266747108:web:e3059bf22c9355354594f1',
    messagingSenderId: '614266747108',
    projectId: 'mk-academy-40f5c',
    authDomain: 'mk-academy-40f5c.firebaseapp.com',
    storageBucket: 'mk-academy-40f5c.firebasestorage.app',
    measurementId: 'G-T3FDSCSRWJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs1919etD_0aVMrIFz0XBPo-cZSWqkNJ0',
    appId: '1:614266747108:android:43dc849d3f1cea674594f1',
    messagingSenderId: '614266747108',
    projectId: 'mk-academy-40f5c',
    storageBucket: 'mk-academy-40f5c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqtBcbv84tYZeBCJJgZaDPmfVrmgmOtrU',
    appId: '1:614266747108:ios:a577c40f2734776a4594f1',
    messagingSenderId: '614266747108',
    projectId: 'mk-academy-40f5c',
    storageBucket: 'mk-academy-40f5c.firebasestorage.app',
    iosBundleId: 'sy.techtoc.mkAcademy',
  );
}
